spring:
  cloud:
    azure:
      cosmos:
        endpoint: ${COSMOS_ENDPOINT}
        key: ${COSMOS_KEY}
        secondaryKey: ${COSMOS_KEY2}
        database: ${COSMOS_DATABASE}
        region: ${COSMOS_REGION}

