spring:
  cloud:
    azure:
      cosmos:
        endpoint: ${{ secrets.COSMOS_ENDPOINT }}
        key: ${{ secrets.COSMOS_KEY }}
        secondaryKey: ${{ secrets.COSMOS_KEY2 }}
        database: ${{ secrets.COSMOS_DATABASE }}
        region: ${{ secrets.COSMOS_REGION }}

