name: Docker Image CI

on:
  workflow_dispatch:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
           login-server: ${{ secrets.ACR_ENDPOINT }}
           username: ${{ secrets.ACR_USERNAME }}
           password: ${{ secrets.ACR_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.ACR_ENDPOINT }}/lorenzo1906acr:${{ github.sha }}
          docker push ${{ secrets.ACR_ENDPOINT }}/lorenzo1906acr:${{ github.sha }}


